---
- name: Install ufw
  ansible.builtin.apt:
    name: ufw
    state: present
    update_cache: true
    cache_valid_time: "{{ apt_cache_valid_time }}"

- name: Allow TCP ports
  community.general.ufw:
    rule: allow
    port: "{{ item | string }}"
    proto: tcp
  loop: "{{ firewall_allowed_tcp_ports }}"

- name: Allow UDP ports
  community.general.ufw:
    rule: allow
    port: "{{ item | string }}"
    proto: udp
  loop: "{{ firewall_allowed_udp_ports }}"

- name: Set default policies and enable ufw
  community.general.ufw:
    state: enabled
    default: deny
    direction: incoming
