---
- name: Install curl
  ansible.builtin.apt:
    name: curl
    state: present
    update_cache: true
    cache_valid_time: "{{ apt_cache_valid_time }}"

- name: Download K3s installer script
  ansible.builtin.get_url:
    url: https://get.k3s.io
    dest: /tmp/k3s-install.sh
    mode: "0755"

- name: Install K3s
  ansible.builtin.command:
    cmd: /tmp/k3s-install.sh
    creates: /etc/systemd/system/k3s.service
  environment:
    INSTALL_K3S_VERSION: "{{ k3s_version }}"

- name: Reload systemd daemon
  ansible.builtin.systemd:
    daemon_reload: true
  changed_when: false

- name: Enable and start K3s
  ansible.builtin.systemd:
    name: k3s
    state: started
    enabled: true

- name: Wait for node to be Ready
  ansible.builtin.command: k3s kubectl wait --for=condition=Ready node --all --timeout=120s
  changed_when: false
